desktops = [
    "GNOME Akame",
    "GNOME Cyborg",
    "GNOME Graphite",
    "GNOME Hack The Box",
    "GNOME Samurai",
    "GNOME Sweet",
    "GNOME XXE",
    "Hyprland",
    "Bspwm",
    "KDE Plasma",
    "MATE",
    "Cinnamon",
    "XFCE",
]
